# Use postgres/example user/password credentials
version: '3.9'

services:

  postgres:
    image: postgres
    restart: always
    ports:
      - "5434:5432"
    container_name: postgres_dev
    environment:
      POSTGRES_USER: postgres_dev
      POSTGRES_PASSWORD: dev

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    container_name: redis_queue



