# Use postgres/example user/password credentials
version: '3.9'

services:

  postgres:
    image: postgres
    restart: always
    ports:
      - "5434:5432"
    container_name: blog_application_development
    environment:
      POSTGRES_USER: blog_application_development
      POSTGRES_PASSWORD: password



