# Use postgres/example user/password credentials
version: '3.9'

services:

  postgres:
    image: postgres
    restart: always
    ports:
      - "5434:5432"
    container_name: postgres_dev
    environment:
      POSTGRES_USER: postgres_dev
      POSTGRES_PASSWORD: dev

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    container_name: redis_queue


  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      BLOG_APPLICATION_DATABASE_PASSWORD: dev
      RAILS_MASTER_KEY: CHANGE_ME
      REDIS_URL: redis://redis:6379/1


  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec sidekiq
    depends_on:
      - redis
      - app
    environment:
      BLOG_APPLICATION_DATABASE_PASSWORD: dev
      RAILS_MASTER_KEY: CHANGE_ME
      REDIS_URL: redis://redis:6379/1